name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokemon-pokedex-cicd"
          heroku_email: "oscarjaureguia@gmail.com"
          healthcheck: "https://pokemon-pokedex-cicd.herokuapp.com/health"
          checkstring: "ok!"
          delay: 5

