name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, syncronize]

jobs:
  build:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokemon-pokedex-cicd"
          heroku_email: "oscarjaureguia@gmail.com"
          healthcheck: "https://pokemon-pokedex-cicd.herokuapp.com/health"
          checkstring: "ok!"
          delay: 5
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
