name: Testing stuff

on:
  push:
    branches:
      - new-feature

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: message contains "#skip"
        if: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}
        run: echo "Should be skipped"