name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checking messages
        env: 
          MESSAGES: ${{ join(toJson(github.event.commits.*.message), ', ') }}
          CONTAINS: ${{ contains(join(toJson(github.event.commits.*.message), ', '), '#skip') }}
        run: |
          echo "$MESSAGES"
          echo "$CONTAINS"
      - name: message contains "#skip"
        if: ${{ contains(join(toJson(github.event.commits.*.message), ', '), '#skip') }}
        run: echo "Should be skipped"